version: "3.7"

services:
  lockdown:
    build: .
    environment:
      MYSQL_HOSTNAME: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: lockdown
      MYSQL_USERNAME: lockdown
      MYSQL_PASSWORD: lockdown
    ports:
      - "80:80"
    networks:
      - frontend
      - backend
    depends_on:
      - mysql

  mysql:
    image: mysql
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: lockdown
      MYSQL_DATABASE: lockdown
      MYSQL_USER: lockdown
      MYSQL_PASSWORD: lockdown
    networks:
      - backend

volumes:
  mysql:

networks:
  frontend:
  backend:
